<?php
require_once dirname(__DIR__).'/config.php';
require_admin();
$pageTitle = $pageTitle ?? 'Admin Panel';
$active = basename($_SERVER['PHP_SELF']);
$signedInFullName = $_SESSION['admin_name'] ?? $_SESSION['SSC_name'] ?? 'Admin';
$signedInParts = preg_split('/\\s+/', trim($signedInFullName));
$signedInFirstName = $signedInParts[0] ?? 'Admin';
$links = [
  ['index.php','Dashboard','M3 13h8V3H3zm0 8h8v-6H3zm10 0h8V11h-8zm0-18v6h8V3z'],
  ['students.php','Students','M12 12a5 5 0 1 0-5-5a5 5 0 0 0 5 5m-7 8a7 7 0 0 1 14 0z'],
  ['ssc_users.php','SSC Accounts','M16 11a4 4 0 1 0-3.9-4.8A5 5 0 0 0 8 9a4 4 0 1 0-3.9 4.8A6 6 0 0 0 0 19h8a6 6 0 0 0-2.3-4.7A4 4 0 0 0 8 13'],
  ['events.php','Events & Participants','M19 3h-1V1h-2v2H8V1H6v2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2m0 16H5V9h14z'],
  ['attendance.php','Attendance Reports','M19 3H5a2 2 0 0 0-2 2v14l4-4h12a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2'],
  ['payments.php','Fines & Payments','M4 4h16v16H4zm3 3v10h10V7z'],
  ['clearance.php','Clearance','M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2m-1 15l-5-5l1.4-1.4L11 14.2l6.6-6.6L19 9z'],
  ['activity_logs.php','Events History','M4 4h16v16H4zm3 3v2h10V7zm0 4v2h10v-2zm0 4v2h7v-2z']
  ,['settings.php','Settings','M12 15.5a3.5 3.5 0 1 0 0-7a3.5 3.5 0 0 0 0 7m8.5-3.5c0-.5-.1-1-.2-1.4l2-1.5l-2-3.4l-2.4 1a8 8 0 0 0-2.4-1.4L15.2 2h-4l-.4 3.3a8 8 0 0 0-2.4 1.4l-2.4-1l-2 3.4l2 1.5A7 7 0 0 0 6.3 12c0 .5.1 1 .2 1.4l-2 1.5l2 3.4l2.4-1a8 8 0 0 0 2.4 1.4l.4 3.3h4l.4-3.3a8 8 0 0 0 2.4-1.4l2.4 1l2-3.4l-2-1.5c.1-.4.2-.9.2-1.4z']
];
if (empty($_SESSION['admin_id'])) { $links = array_values(array_filter($links, function ($link) { return !in_array($link[0], ['ssc_users.php', 'events.php'], true); })); }
if (empty($_SESSION['admin_id'])) { $links[] = ['request_event.php','Request Event','M19 3h-1V1h-2v2H8V1H6v2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2m0 16H5V9h14z']; }
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><title><?php echo h($pageTitle); ?> - Admin</title><script src="https://cdn.tailwindcss.com"></script><script src="../assets/app.js" defer></script><style>*,*::before,*::after{box-sizing:border-box}html{overflow-x:hidden}body{overflow-x:hidden}aside{transition:all .25s ease}.admin-content{min-width:0}.admin-content main{min-width:0;overflow-x:hidden}.admin-content table{white-space:nowrap}.admin-content .overflow-x-auto{max-width:100%;-webkit-overflow-scrolling:touch}.admin-content input,.admin-content select,.admin-content textarea,.admin-content button{max-width:100%}body.sidebar-collapsed aside{width:5rem!important}body.sidebar-collapsed .sb-text,body.sidebar-collapsed .sb-quick{display:none}body.sidebar-collapsed aside a{justify-content:center}body.sidebar-collapsed .admin-content{margin-left:5rem!important}@media(max-width:767px){.admin-aside{display:none!important}.mobile-open .admin-aside{display:flex!important;position:fixed;inset:0 auto 0 0;width:min(19rem,88vw);z-index:50;overflow-y:auto}.mobile-open .mobile-shade{display:block!important}.admin-content{margin-left:0!important}.admin-content header{position:relative}.admin-content header>div{align-items:stretch!important;padding-left:.75rem!important;padding-right:.75rem!important}.admin-content header>div>div:first-child{min-width:0}.admin-content header>div>div:first-child>div:last-child{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.admin-content header>div>div:last-child{width:100%;min-width:0;flex-wrap:wrap;justify-content:center}.admin-content header .js-clock{font-size:.72rem}.admin-content main{padding:.75rem!important}.admin-content footer>div{flex-wrap:wrap;gap:.5rem;padding:.75rem 1rem}.admin-content .grid{min-width:0}.admin-content form{min-width:0}.admin-content input,.admin-content select,.admin-content textarea,.admin-content button{min-height:2.75rem}.admin-content h1,.admin-content h2,.admin-content h3{line-height:1.2}.admin-content .rounded-2xl,.admin-content .rounded-3xl{border-radius:1rem}.admin-content .p-5,.admin-content .p-6{padding:1rem}.admin-content table{font-size:.75rem}.admin-content th,.admin-content td{padding-left:.55rem!important;padding-right:.55rem!important}.admin-content .overflow-x-auto{margin-left:-.25rem;margin-right:-.25rem;padding-bottom:.25rem}.admin-content .flex-wrap{row-gap:.5rem}}@media(min-width:768px){.admin-content footer>div{flex-wrap:wrap;gap:.75rem}}.btn-ghost{background:#fff}.btn-ghost:hover{background:#f8fafc}.ease-color{transition:color .2s ease}</style></head>
<body class="bg-slate-100 text-slate-800 opacity-0 translate-y-1"><div class="min-h-screen"><div class="mobile-shade fixed inset-0 z-40 hidden bg-slate-950/40" data-close-menu></div>
<aside class="admin-aside fixed left-0 top-0 z-40 hidden h-screen w-72 flex-col border-r border-slate-700 bg-gradient-to-b from-slate-950 via-slate-900 to-indigo-900 text-slate-100 shadow-xl md:flex"><div class="flex h-full flex-col"><div class="flex flex-shrink-0 items-center gap-3 px-5 py-6"><div class="flex h-11 w-11 items-center justify-center overflow-hidden rounded-xl bg-indigo-500 font-bold shadow-inner">SSC</div><div><div class="sb-text text-sm uppercase tracking-widest text-slate-300">SSC Event Attendance</div><div class="sb-text text-lg font-bold leading-5"><?php echo !empty($_SESSION['admin_id']) ? 'Admin' : 'SSC Officer'; ?></div></div></div><nav class="flex-1 space-y-1 overflow-y-auto px-3 py-2"><?php foreach($links as $link): ?><a href="<?php echo h($link[0]); ?>" title="<?php echo h($link[1]); ?>" class="flex items-center gap-3 rounded-lg px-3 py-2 transition hover:bg-white/10 <?php echo $active===$link[0]?'bg-white/10':''; ?>"><svg width="18" height="18" viewBox="0 0 24 24" class="opacity-90"><path fill="currentColor" d="<?php echo h($link[2]); ?>"/></svg><span class="sb-text"><?php echo h($link[1]); ?></span></a><?php endforeach; ?></nav><div class="flex-shrink-0 border-t border-slate-700"><div class="sb-quick mx-4 my-4 rounded-xl bg-white/5 p-3 text-sm"><div class="text-slate-200">Quick Scan</div><div class="mt-2 flex flex-wrap gap-2"><a href="../scan.php" class="rounded bg-emerald-500/90 px-3 py-1 text-xs text-white transition hover:bg-emerald-400">SCAN</a><a href="../index.php" class="rounded bg-white/10 px-3 py-1 text-xs text-white transition hover:bg-white/20">HOME</a></div></div><div class="px-5 py-4 text-xs text-slate-300/80">&copy; <?php echo date('Y'); ?> SSC Event Attendance</div></div></div></aside>
<div class="admin-content flex min-h-screen flex-col md:ml-72"><header class="sticky top-0 z-10 border-b border-slate-200 bg-white shadow-sm"><div class="mx-auto flex max-w-7xl flex-col items-center justify-between gap-3 px-4 py-3 sm:flex-row"><div class="flex items-center gap-3"><button id="sbToggle" class="rounded-lg border border-slate-200 bg-slate-50 p-2 text-slate-700 transition hover:bg-slate-100" title="Toggle sidebar"><span class="sr-only">Toggle sidebar</span><svg width="18" height="18" viewBox="0 0 24 24"><path fill="currentColor" d="M3 6h18v2H3zm0 5h18v2H3zm0 5h18v2H3z"/></svg></button><div class="text-lg font-semibold text-slate-900"><?php echo h($pageTitle); ?></div></div><div class="flex flex-col items-center gap-3 text-sm text-slate-600 sm:flex-row"><div class="whitespace-nowrap"><span class="js-clock" data-tz="Asia/Manila" aria-live="polite">Loading live time...</span></div><div class="whitespace-nowrap">Signed in as <span class="font-medium text-slate-900"><?php echo h($signedInFirstName); ?></span></div><a href="../logout.php" class="inline-flex rounded-full border border-slate-200 bg-slate-100 px-4 py-2 text-slate-700 transition hover:bg-slate-200">Logout</a></div></div></header><main class="mx-auto w-full max-w-7xl flex-1 p-4 md:p-8"><?php echo $content; ?></main><footer class="mt-auto border-t bg-white/70"><div class="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 text-sm"><div class="text-slate-600">SSC Event Attendance - Admin Management</div><div class="inline-flex items-center gap-2 text-slate-500"><span class="h-2 w-2 rounded-full bg-violet-600"></span><span>Tailwind Theme</span></div></div></footer></div></div>
<script>(function(){const body=document.body,key='admin_sb_collapsed';if(localStorage.getItem(key)==='1')body.classList.add('sidebar-collapsed');const btn=document.getElementById('sbToggle');if(btn)btn.addEventListener('click',()=>{if(window.matchMedia('(max-width: 767px)').matches){body.classList.toggle('mobile-open')}else{body.classList.toggle('sidebar-collapsed');localStorage.setItem(key,body.classList.contains('sidebar-collapsed')?'1':'0')}});document.querySelectorAll('[data-close-menu]').forEach(el=>el.addEventListener('click',()=>body.classList.remove('mobile-open')));function tick(){document.querySelectorAll('.js-clock').forEach(el=>{try{el.textContent=new Intl.DateTimeFormat('en-PH', {dateStyle:'medium',timeStyle:'medium',timeZone:el.dataset.tz||'Asia/Manila'}).format(new Date())}catch(e){el.textContent=new Date().toLocaleString()}})}tick();setInterval(tick,1000);window.addEventListener('load',()=>document.body.classList.remove('opacity-0','translate-y-1'))})();</script></body></html>
