<?php
require_once dirname(__DIR__).'/config.php';
$conn=db();
$message='';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='sign'){
    $id=(int)$_POST['student_id'];
    $q=$conn->prepare("SELECT COALESCE(SUM(f.amount),0)-COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.fine_id=f.id),0) balance FROM fines f WHERE f.student_id=? AND f.status<>'WAIVED'");
    $q->bind_param('i',$id);$q->execute();$balance=(float)$q->get_result()->fetch_assoc()['balance'];
    if($balance<=0){
        $s=$conn->prepare("INSERT INTO clearance(student_id,status,signed_at,signed_by) VALUES(?,'SIGNED',NOW(),?) ON DUPLICATE KEY UPDATE status='SIGNED',signed_at=NOW(),signed_by=VALUES(signed_by)");
        $admin=(int)$_SESSION['admin_id'];$s->bind_param('ii',$id,$admin);$s->execute();$message='Clearance signed.';
    }else{$message='Clearance remains on hold because the balance is not fully paid.';}
}
$search=trim($_GET['search']??'');$like='%'.$search.'%';
$q=$conn->prepare("SELECT s.id,s.student_no,s.first_name,s.last_name,COALESCE(SUM(f.amount),0) total_fines,COALESCE(SUM((SELECT COALESCE(SUM(p.amount),0) FROM payments p WHERE p.fine_id=f.id)),0) total_paid,COALESCE(c.status,'PENDING') clearance_status FROM students s LEFT JOIN fines f ON f.student_id=s.id LEFT JOIN clearance c ON c.student_id=s.id WHERE (?='' OR s.student_no LIKE ? OR s.first_name LIKE ? OR s.last_name LIKE ?) GROUP BY s.id,c.status ORDER BY s.last_name,s.first_name");
$q->bind_param('ssss',$search,$like,$like,$like);$q->execute();$rows=$q->get_result();
$pageTitle='Fines & Clearance';ob_start();
?><div class="space-y-6"><?php if($message):?><div class="rounded-lg bg-indigo-100 p-3 text-indigo-800"><?php echo h($message);?></div><?php endif;?><div class="rounded-2xl bg-white p-5 shadow"><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div class="text-lg font-semibold">Clearance status</div><form class="flex w-full gap-2 sm:w-64"><input name="search" value="<?php echo h($search);?>" placeholder="Search student" aria-label="Search Student ID or name" class="min-w-0 flex-1 rounded border px-2 py-1 text-sm"><button class="rounded bg-slate-900 px-3 py-1 text-sm text-white">Search</button></form></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="border-b text-left"><th class="px-2 py-2">Student</th><th class="px-2 py-2">Total fines</th><th class="px-2 py-2">Paid</th><th class="px-2 py-2">Outstanding</th><th class="px-2 py-2">Status</th><th></th></tr></thead><tbody><?php while($r=$rows->fetch_assoc()):$balance=(float)$r['total_fines']-(float)$r['total_paid'];$eligible=$balance<=0;?><tr class="border-b"><td class="px-2 py-3 font-medium"><?php echo h($r['last_name'].', '.$r['first_name']);?><div class="text-xs text-slate-500"><?php echo h($r['student_no']);?></div></td><td class="px-2 py-3">&#x20B1;<?php echo number_format($r['total_fines'],2);?></td><td class="px-2 py-3">&#x20B1;<?php echo number_format($r['total_paid'],2);?></td><td class="px-2 py-3">&#x20B1;<?php echo number_format(max(0,$balance),2);?></td><td class="px-2 py-3"><?php echo h($r['clearance_status']);?></td><td class="px-2 py-3"><?php if($eligible):?><form method="post"><input type="hidden" name="action" value="sign"><input type="hidden" name="student_id" value="<?php echo (int)$r['id'];?>"><button class="rounded bg-emerald-700 px-3 py-1 text-xs text-white">Sign clearance</button></form><?php else:?><span class="text-xs text-rose-700">ON HOLD - UNPAID FINE</span><?php endif;?></td></tr><?php endwhile;?></tbody></table></div></div></div><?php $content=ob_get_clean();include __DIR__.'/_layout.php';