<?php
require_once __DIR__.'/config.php';
$conn = db();
$organizationName = get_ssc_setting('organization_name', 'Student Entry and Exit Using a Barcode and SMS Integration System');
$event = active_event($conn);
$registered = 0;
if ($event) {
    $query = $conn->prepare('SELECT COUNT(*) c FROM event_students WHERE event_id=?');
    $query->bind_param('i', $event['id']);
    $query->execute();
    $registered = (int)$query->get_result()->fetch_assoc()['c'];
    $incomingEvents = 0;
}
$incomingEvent = $conn->query("SELECT event_name,event_date,start_time FROM events WHERE status IN ('UPCOMING','DRAFT') AND CONCAT(event_date,' ',start_time) >= NOW() ORDER BY event_date ASC, start_time ASC LIMIT 1")->fetch_assoc();
$todayEvent = $conn->query("SELECT event_name,status FROM events WHERE event_date=CURDATE() AND status IN ('ACTIVE','UPCOMING','DRAFT') ORDER BY FIELD(status,'ACTIVE','UPCOMING','DRAFT'), start_time LIMIT 1")->fetch_assoc();
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo h($organizationName); ?></title>
<script src="https://cdn.tailwindcss.com"></script>
<script src="assets/app.js" defer></script>
<style>
  .aurora{position:absolute;filter:blur(60px);opacity:.55}.a1{width:60vw;height:60vw;left:-15vw;top:-15vh;background:radial-gradient(closest-side,rgba(99,102,241,.5),transparent 60%)}.a2{width:50vw;height:50vw;right:-10vw;top:-10vh;background:radial-gradient(closest-side,rgba(16,185,129,.55),transparent 60%)}.a3{width:45vw;height:45vw;left:10vw;bottom:-15vh;background:radial-gradient(closest-side,rgba(245,158,11,.5),transparent 60%)}.glass{background-color:rgba(255,255,255,.64);backdrop-filter:saturate(150%) blur(18px)}.hero-modal{box-shadow:0 30px 80px rgba(15,23,42,.2),0 8px 24px rgba(79,70,229,.12),inset 0 1px rgba(255,255,255,.95)}.lift{transition:transform .25s ease,box-shadow .25s ease}.lift:hover{transform:translateY(-5px);box-shadow:0 18px 32px rgba(15,23,42,.14)}a[href="admin/index.php"]>div:first-child>div:last-child{margin-top:.75rem}a[href="scan.php"]>div:last-child{flex-direction:row-reverse}@media(max-width:640px){.hero-modal{border-radius:1.25rem;padding:1.25rem}.hero-modal h1{font-size:2rem;line-height:1.1;overflow-wrap:anywhere}.hero-modal p{line-height:1.5}.hero-modal .grid{gap:.75rem}.hero-modal a{min-height:8.5rem;padding:1rem}.hero-modal a>div:first-child>div{overflow-wrap:anywhere}.hero-modal .text-xl{font-size:1.05rem}.hero-modal .text-2xl{font-size:1.35rem}}
</style>
</head>
<body class="min-h-screen bg-slate-50 text-slate-800 opacity-0 translate-y-1">
<div class="relative min-h-screen overflow-hidden"><div class="aurora a1"></div><div class="aurora a2"></div><div class="aurora a3"></div><div class="relative flex min-h-screen items-center"><main class="mx-auto w-full max-w-5xl p-3 sm:p-6"><section class="hero-modal glass rounded-[2rem] border border-white/80 p-5 text-center sm:p-8 md:p-10"><div class="inline-flex items-center gap-2 rounded-full bg-indigo-100 px-3 py-1 text-xs font-medium text-indigo-700 sm:text-sm">PHP + MySQL · Tailwind</div><h1 class="mx-auto mt-4 max-w-3xl text-3xl font-extrabold leading-tight tracking-tight sm:text-4xl md:text-5xl"><?php echo h($organizationName); ?></h1><p class="mx-auto mt-3 max-w-2xl text-sm leading-6 text-slate-600 sm:text-base">Fast, smooth, and secure attendance scanning for authorized school events and activities.</p><div id="clock" class="mt-2 text-xs text-slate-500"></div><div class="mx-auto mt-7 grid max-w-4xl gap-4 md:grid-cols-2">
<a href="scan.php" class="lift group relative flex min-h-36 flex-col justify-between rounded-2xl border border-emerald-200 bg-white/70 p-4 text-left shadow-sm hover:bg-white sm:p-5 <?php echo !$event?'pointer-events-none opacity-60':''; ?>"><div><div class="flex items-center gap-2 text-emerald-700"><svg width="22" height="22" viewBox="0 0 24 24"><path fill="currentColor" d="M12 12a5 5 0 1 0-5-5a5 5 0 0 0 5 5m-7 8a7 7 0 0 1 14 0z"/></svg><div class="text-lg font-semibold sm:text-xl">Student Entry / Exit</div></div><div class="mt-3 flex justify-center gap-4 text-xs font-bold tracking-[.18em]"><span class="inline-flex items-center gap-1 text-emerald-600"><svg width="14" height="14" viewBox="0 0 24 24"><path fill="currentColor" d="M10 17v-6H6l6 6h-4v6z"/></svg>ENTRY</span><span class="inline-flex items-center gap-1 text-orange-500"><svg width="14" height="14" viewBox="0 0 24 24"><path fill="currentColor" d="M14 7v6h4l-6 6l-6-6h4V7z"/></svg>EXIT</span></div></div><div class="mt-2 flex items-center justify-between gap-3 text-sm text-slate-500"><span>Ready for scanner input →</span><span id="cameraLaunch" role="button" tabindex="0" title="Open camera scanner" aria-label="Open camera scanner" class="inline-flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-full border border-emerald-200 bg-emerald-50 text-emerald-700 shadow-sm transition hover:bg-emerald-100"><svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M9 4l1.5-2h3L15 4h3a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3zm3 4a5 5 0 1 0 0 10a5 5 0 0 0 0-10m0 2.2a2.8 2.8 0 1 1 0 5.6a2.8 2.8 0 0 1 0-5.6"/></svg></span></div></a>
<a href="admin/index.php" class="lift group flex min-h-36 flex-col justify-between rounded-2xl border border-violet-200 bg-white/70 p-4 text-left shadow-sm transition hover:bg-white hover:shadow-xl sm:p-5"><div><div class="flex items-center gap-2 text-violet-700"><svg width="22" height="22" viewBox="0 0 24 24"><path fill="currentColor" d="M12 12a5 5 0 1 0-5-5a5 5 0 0 0 5 5m-7 8a7 7 0 0 1 14 0z"/></svg><div class="text-xl font-semibold">Admin Dashboard</div></div><div class="text-center text-slate-500">Manage students and logs</div></div><div class="mt-2 self-end text-sm text-slate-500 transition group-hover:translate-x-0.5">Open dashboard →</div></a>
</div><div class="mx-auto mt-6 grid max-w-4xl gap-3 text-left sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-xl border border-white/70 bg-white/60 p-4"><div class="text-xs uppercase tracking-widest text-slate-500">Event status</div><div class="mt-1 font-semibold <?php echo $event?'text-emerald-700':'text-slate-600'; ?>"><?php echo $event?'ACTIVE':'NO ACTIVE EVENT'; ?></div></div><div class="rounded-xl border border-white/70 bg-white/60 p-4"><div class="text-xs uppercase tracking-widest text-slate-500">Registered students</div><div class="mt-1 text-2xl font-bold"><?php echo number_format($registered); ?></div></div><div class="rounded-xl border border-white/70 bg-white/60 p-4"><div class="text-xs uppercase tracking-widest text-slate-500">Event today</div><?php if ($todayEvent): ?><div class="mt-1 font-semibold text-indigo-700"><?php echo h($todayEvent['event_name']); ?></div><?php else: ?><div class="mt-1 font-semibold text-slate-500">No event today</div><?php endif; ?></div><div class="rounded-xl border border-white/70 bg-white/60 p-4"><div class="text-xs uppercase tracking-widest text-slate-500">Incoming events</div><?php if ($incomingEvent): ?><div class="mt-1 font-semibold text-violet-700"><?php echo h($incomingEvent['event_name']); ?></div><div class="mt-1 text-xs text-slate-500"><?php echo h($incomingEvent['event_date']); ?></div><?php else: ?><div class="mt-1 font-semibold text-slate-500">No incoming event</div><?php endif; ?></div></div></section></main></div></div>
<script>const clock=document.getElementById('clock');function tick(){clock.textContent=new Date().toLocaleString('en-PH',{dateStyle:'medium',timeStyle:'medium'})}tick();setInterval(tick,1000);const scanCard=document.querySelector('a[href="scan.php"]'),scanTitle=scanCard&&scanCard.querySelector('.text-lg');if(scanTitle)scanTitle.textContent='Student Entry / Exit →';const readyText=document.querySelector('a[href="scan.php"]>div:last-child>span:first-child');if(readyText)readyText.textContent='Ready for scanner input →';const cameraLaunch=document.getElementById('cameraLaunch');if(cameraLaunch){const openCamera=event=>{event.preventDefault();event.stopPropagation();window.location.href='scan.php?camera=1'};cameraLaunch.addEventListener('click',openCamera);cameraLaunch.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){openCamera(event)}})}window.addEventListener('load',()=>document.body.classList.remove('opacity-0','translate-y-1'));</script>
</body><script>const entryIcon=document.querySelector('a[href="scan.php"] .text-emerald-600 svg path');const exitIcon=document.querySelector('a[href="scan.php"] .text-orange-500 svg path');if(entryIcon){entryIcon.setAttribute('d','M12 21V7.8l-4.6 4.6L6 11l6-6l6 6l-1.4 1.4L13 7.8V21z');entryIcon.setAttribute('fill','none');entryIcon.setAttribute('stroke','currentColor');entryIcon.setAttribute('stroke-width','2.6');entryIcon.setAttribute('stroke-linecap','round');entryIcon.setAttribute('stroke-linejoin','round')}if(exitIcon){exitIcon.setAttribute('fill','none');exitIcon.setAttribute('stroke','currentColor');exitIcon.setAttribute('stroke-width','2.6');exitIcon.setAttribute('stroke-linecap','round');exitIcon.setAttribute('stroke-linejoin','round')}</script></html>
