<?php
require_once dirname(__DIR__).'/config.php';
require_admin();
if (empty($_SESSION['ssc_id'])) { http_response_code(403); exit('SSC user access required.'); }
$conn = db(); $message=''; $error='';
if ($_SERVER['REQUEST_METHOD']==='POST') {
  $name=trim($_POST['event_name']??''); $description=trim($_POST['description']??''); $type=trim($_POST['event_type']??''); $venue=trim($_POST['venue']??''); $date=$_POST['event_date']??''; $start=$_POST['start_time']??''; $end=$_POST['end_time']??''; $inStart=$_POST['scan_in_start']??''; $inEnd=$_POST['scan_in_end']??''; $outStart=$_POST['scan_out_start']??''; $outEnd=$_POST['scan_out_end']??''; $fine=(float)($_POST['fine_amount']??0);
  if (!$name||!$date||!$start||!$end||!$inStart||!$inEnd||!$outStart||!$outEnd||$fine<0||$start>$end||$inStart>$inEnd||$outStart>$outEnd) {$error='Complete the request details and use valid time ranges.';} else { $stmt=$conn->prepare('INSERT INTO event_requests(ssc_user_id,event_name,description,event_type,venue,event_date,start_time,end_time,scan_in_start,scan_in_end,scan_out_start,scan_out_end,fine_amount) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)'); $uid=(int)$_SESSION['ssc_id']; $stmt->bind_param('isssssssssssd',$uid,$name,$description,$type,$venue,$date,$start,$end,$inStart,$inEnd,$outStart,$outEnd,$fine); if($stmt->execute()){$message='Event request submitted. Wait for Admin approval.';}else{$error='Unable to submit the event request.';} }
}
$pageTitle='Request Event'; ob_start(); ?>
<div class="space-y-6"><div class="rounded-2xl bg-white p-5 shadow"><div class="mb-1 text-lg font-semibold">Request an event</div><p class="mb-4 text-sm text-slate-500">Your request must be reviewed and approved by an Admin before the event can be created.</p><?php if($message):?><div class="mb-4 rounded-lg bg-emerald-100 p-3 text-emerald-800"><?php echo h($message);?></div><?php endif;?><?php if($error):?><div class="mb-4 rounded-lg bg-rose-100 p-3 text-rose-800"><?php echo h($error);?></div><?php endif;?><form method="post" class="grid gap-3 md:grid-cols-4"><input name="event_name" required placeholder="Event name" class="rounded border px-3 py-2 md:col-span-2"><input name="event_type" placeholder="Event type" class="rounded border px-3 py-2"><input name="venue" placeholder="Venue" class="rounded border px-3 py-2"><textarea name="description" placeholder="Description" class="rounded border px-3 py-2 md:col-span-4"></textarea><label class="text-sm">Event date<input name="event_date" type="date" required class="mt-1 w-full rounded border px-3 py-2"></label><label class="text-sm">Start time<input name="start_time" type="time" required class="mt-1 w-full rounded border px-3 py-2"></label><label class="text-sm">End time<input name="end_time" type="time" required class="mt-1 w-full rounded border px-3 py-2"></label><label class="text-sm">Fine amount<input name="fine_amount" type="number" min="0" step="0.01" value="0" class="mt-1 w-full rounded border px-3 py-2"></label><label class="text-sm">Scan-in opens<input name="scan_in_start" type="time" required class="mt-1 w-full rounded border px-3 py-2"></label><label class="text-sm">Scan-in closes<input name="scan_in_end" type="time" required class="mt-1 w-full rounded border px-3 py-2"></label><label class="text-sm">Scan-out opens<input name="scan_out_start" type="time" required class="mt-1 w-full rounded border px-3 py-2"></label><label class="text-sm">Scan-out closes<input name="scan_out_end" type="time" required class="mt-1 w-full rounded border px-3 py-2"></label><button class="rounded bg-indigo-700 px-4 py-2 font-semibold text-white hover:bg-indigo-600 md:col-span-4">Submit event request</button></form></div></div><?php $content=ob_get_clean(); include __DIR__.'/_layout.php';
